### ISSUE TITLE
Cannot search/find through content-editable elements

### ISSUE THREAD

**Issue by smblott-github** [philc/vimium#1410]
Reproduce:
- Go [here](http://demo.hongkiat.com/html5-editable-content/index2.html).
- Search for "muffin": `/muffin<Enter>`.
- Type `n` to find the next match.

Oops, you've been dropped into insert mode.

This stems from this [change](https://github.com/philc/vimium/commit/512aa9919ac19335ef86048fb41ffa051b60dd3a), from this [PR](https://github.com/philc/vimium/pull/1247) addressing this [issue](https://github.com/philc/vimium/issues/1245).

**Comment by philc** [comment]
Nice find!

**Comment by mrmr1993** [comment]
This is fixed in #1273

**Comment by smblott-github** [comment]
> This is fixed in #1273.

I tried #1273.  Doesn't fix the problem for me, unfortunately.

**Comment by mrmr1993** [comment]
> ... when using `n`.

Apologies, I missed that.

I designed #1250 with this use case specifically in mind, can you take a look at that?

**Comment by smblott-github** [comment]
BTW: This is fixed in my follow-on branch to #1407, [here](https://github.com/smblott-github/vimium/tree/modes).
