### ISSUE TITLE
in feedly.com, the menu to "mark all articles as read" is not marked when pressing 'f'.

### ISSUE THREAD

**Issue by apporc** [philc/vimium#1688]
RT. Thanks.

**Comment by smblott-github** [comment]
Confirmed...

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7834664/7d4bfa7e-0469-11e5-8183-0db6172a5990.png)

This is the element:

![snapshot](https://cloud.githubusercontent.com/assets/2641335/7834681/99529034-0469-11e5-99a1-539bb97c2568.png)

**Comment by mrmr1993** [comment]
Looks like #1405 (or #1409) should fix this once rebased onto `master`.

**Comment by smblott-github** [comment]
@mrmr1993. Unfortunately, #1405 doesn't fix this (I haven't checked #1409).

(TBH, both of those PRs are big honking beasts, and they scare me.)

**Comment by mrmr1993** [comment]
From a brief look at the page, it looks like supporting this is going to be very hard for us:

* pages use a single, centralised `click` event listener (on `window`) to handle all click events
* the centralised event listener marks elements in a non-standard way (`data-uri` for links, `data-page-action` for whatever the mark as read button is, etc.) which we won't want to support for any other sites
* not all elements with `data-*` attributes are clickable
* buttons, some links, etc. aren't keyboard accessible (except using their provided keyboard shortcuts)
* they provide no accessibility data on clickable elements.

To get this right in the codebase will add quite a lot of code weight, all to support a single site, and I think we would be wise not to try and solve it in Vimium's codebase. I can think of a couple of ways to go about addressing this:
* ask Feedly to make their website accessibility-friendly, using `role="link"` or `role="button"` as necessary
* write a TamperMonkey script/chrome extension that adds these `role` attributes to the necessary elements automatically
  - the `data-*` handlers that need this are listed from a function called `aK` in one of their source files, as far as I can see.

**Comment by smblott-github** [comment]
Thanks for the excellent analysis, @mrmr1993.

It might be worth posting an issue over at [feedly](https://feedly.uservoice.com/forums/192636-suggestions).  A proposal based on accessibility (rather than Vimium's needs) might fly better.

**Comment by philc** [comment]
Great analysis, and yes I agree -- let's not over-optimize for folks who aren't using reasonable expressions of what a link is. Their DOM usage is pretty unorthodox...
