### ISSUE TITLE
Yank doesn't work in firefox 57.0

### ISSUE THREAD

**Issue by danielbaniel** [philc/vimium#2833]
When I yank I see the vimium tooltip at the bottom - "yanked ..."

However I get nothing on my clipboard.

Build identifier: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:57.0) Gecko/20100101 Firefox/57.0
Vimium: 1.61.1

**Comment by wnereiz** [comment]
Same here on GNU/Linux version.

**Comment by finix14** [comment]
Same here..

**Comment by azdanov** [comment]
Same here.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:58.0) Gecko/20100101 Firefox/58.0
Vimium: 1.61.1

**Comment by smblott-github** [comment]
Yank is broken on FF; a fix was merged on Saturday and will be released soon.

**Comment by vcunat** [comment]
Close?

**Comment by vcunat** [comment]
Hmm, actually I currently experience problems on FF with the `yy` command :-/

**Comment by serussell** [comment]
It's also not working with Vivaldi 1.14.1036.3 + X11 (1.19.6-2) + Linux (4.14.10-1-ARCH).  Similar behavior: the plugin appears to work, reports it's yanked, but does not change any of the X clipboards (primary, secondary, or clipboard).

**Comment by neilhwatson** [comment]
Seems to be with certain sites. For example I can't yank a specific tweet from twitter. I'm using FF 59.0.2 on Linux

**Comment by matt-snider** [comment]
Also having this issue in FF 63.0.3 -- reports the text has been yanked, but isn't saved to the clipboard. Did anyone find a cause or fix for this?

**Comment by vcunat** [comment]
For me it's still flaky &ndash; sometimes it gets into the clipboard and sometimes doesn't; it's quite annoying for my habits.  I haven't dug into causes; I've got basically no JS/... knowledge.

**Comment by circld** [comment]
here's a concrete case where FF 65.0 fails to yank the URL (`yy`):

1. navigate to https://issues.apache.org/jira/projects/KAFKA/issues
2. click on any ticket that isn't the "default" (i.e., the one in the URL)
3. `yy`
4. check whether the yanked URL matches the ticket you previously clicked on (in my case, *it does not*)
5. now click on the ticket link above the title to open the ticket itself. for instance:
![image](https://user-images.githubusercontent.com/5423134/52574161-4b8e0180-2de1-11e9-8a46-57a1de918e66.png)
6. when the ticket opens, `yy` once more (in my case, *it does not*)
7. click anywhere within the page and try again; now it should yank the URL correctly

i've noticed that this behavior seems to be consistent across JIRA ticketing systems. in some cases, it seems like it may be a focus problem (e.g., step 7 "fixes" the issue).

**Comment by magras** [comment]
I had even more bizarre behavior: after yanking current url (`yy`) and trying to open it in a new tab (`P`), I've got [google page](https://www.google.com/webhp). Probably google came from empty default search engine. Then I waited for a few seconds and opened new tab again (`P`). I've got wrong url described by @circld in step 4.

**Comment by vcunat** [comment]
What I noticed is that when I `yy`, firefox won't react to `P` until the "yanked" notification label disappears.

**Comment by innaterebel** [comment]
@magras What browser are you using? I start experiencing exactly what you describe in the latest Dev version of Chrome, I thought it was some regression on Chrome's nightly side.

**Comment by vcunat** [comment]
Well, this thread is _supposedly_ about Firefox.

**Comment by innaterebel** [comment]
Yes, so it surprised me a supposed Firefox user was describing exactly what I am seeing on Chrome, it may indicate Chrome is changing its clipboard API to match that of Firefox.

**Comment by magras** [comment]
@innaterebel, I'm using Fireforx 65.0.1 (64-bit) on different OS'es. I can reproduce [behaviour described earlier](https://github.com/philc/vimium/issues/2833#issuecomment-464462596) only with link provided by @circld.

Also I can add to [this observation](https://github.com/philc/vimium/issues/2833#issuecomment-464640257) that firefox will ignore all vimium keybindings, not only `P`. If I mouse click on a page to bring focus back while notification visible, I can `P` immediately.

**Comment by philc** [comment]
Thanks folks for the discussion! This is fixed in #3260, which has been released to the chrome store.

**Comment by philc** [comment]
This went out in v1.64.6 which is live on the Firefox store as of right now.

**Comment by waldauf** [comment]
For me is yank still broken - sometimes works and sometimes never. 

Vimium: 1.64.6
FF: 67.0.4
OS: Archlinux

**Comment by daraul** [comment]
I'm having this problem as well. Sometimes it'll work, sometimes it won't.

Vimium: 1.64.6
FF: 71.0 
OS: Archlinux

**Comment by gdh1995** [comment]
@philc @Mendess2526 https://github.com/philc/vimium/issues/2521#issuecomment-586034031 has just reported the same issue, so I think PR #3277 might not fix the problem on Firefox. Then We may reopen this issue.

I may get some rest time to test it in this weekend.

**Comment by j-cr** [comment]
Vimium 1.66, ff 68, yy doesn't work.

**Comment by xp-vit** [comment]
Vimium 1.67.4 and FF 109.0 (64-bit) yanking doesn't work for me.

Frankly speaking it doesn't work for already some time, but I just decided to report it. When I press "yy" browser shows that link was "Yanked", however nothing appears in clipboard.

Is it some FF security limitation, or we have chances to fix it?

P.S.: Thanks for great plugin!!

**Comment by vcunat** [comment]
You should update, such a problem was solved relatively recently.  Auto-update gave me 1.67.6 and it works for me there again.

**Comment by xp-vit** [comment]
Is there an update available? My FF needs to provide me with any updates for my 1.67.4.

**Comment by anmolmathias** [comment]
i'm still experiencing this problem :\

ver 1.99.997. firefox. ubuntu 24.04 LTS

**Comment by McPhale** [comment]
I'm still seeing this issue as well.
Firefox version:  Firefox developer edition 146.0b5 (64-bit)
OS: Windows 11 Enterprise version 23H2
