### ISSUE TITLE
Firefox : "f" or "F" hint on any link with target="_blank" opens 2 tabs

### ISSUE THREAD

**Issue by danjac** [philc/vimium#2860]
If I open a link with target="_blank" (e.g. on Twitter or Reddit) using hints (either "f" or "F") vimium opens 2 adjacent tabs.

Firefox 57 (Linux/Gnome/Fedora 27)

Vimium 1.62

**Comment by xiongyingfei** [comment]
Same problem here. This is a serious bug as such links are common.

**Comment by smblott-github** [comment]
Does the same thing happen if the target is something other than `"_blank_`?

**Comment by xiongyingfei** [comment]
So far it seems that only "_black" links have the problem.

**Comment by smblott-github** [comment]
This should be fixed in 1.62.8, which is live now.

**Comment by xiongyingfei** [comment]
Unfortunately, no. My vimium has been updated to 1.62.8, but the problem is still there.

This can be tested at bing.com: https://www.bing.com/search?q=hello&qs=n&form=QBLHCN&sp=-1&pq=hello&sc=0-0&sk=&cvid=59D3AE564C6C48BBA96264DF234CDB34

Using "f" to open any search result will result in two tabs. If popup is blocked, firefox will block one tab. However, if we allow popup, two tabs will be created.

Using "F" will not trigger this problem.

Please let me know if you need any further information on this issue.

**Comment by smblott-github** [comment]
Sorry.  My mistake.  I actually forgot to merge the relevant PR.  It's merged now and will be in the next release.

**Comment by danjac** [comment]
Thanks for the quick response!
