### ISSUE TITLE
createTab window and createTab incognito not working in Firefox

### ISSUE THREAD

**Issue by dexterwkearney** [philc/vimium#2894]
Firefox version: 57.0.1
Vimium version: 1.62.8
When: I map a key to "createTab window" or "createTab incognito"
Expected: Pressing that key creates a window or private browsing window
Observed: No tab or window opens whatsoever. However, ? shows the mapped key beside "Manipulating tabs -> Create new tab".
(commands originally added in #2836)

**Comment by ris58h** [comment]
Can confirm. I get 
`Error: Type error for parameter createData (Property "focused" is unsupported by Firefox) for windows.create.`
in console. There is the Firefox [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1253129).

**Comment by dexterwkearney** [comment]
fixed in v1.63

**Comment by quazar0** [comment]
I just want you guys to be aware, I am still seeing this problem in v1.63.3 in FF v60.0.2
