### ISSUE TITLE
`p` and `P` generate search URLs with empty query

### ISSUE THREAD

**Issue by tasusu** [philc/vimium#4120]
**Describe the bug**
The keys `p` and `P` produce search URLs with an empty query. For example, if "dog" is in your clipboard, pressing `p` should open Google's search result for "dog" (https://www.google.com/search?q=dog). However, it instead opens a search URL with an empty query (https://www.google.com/search?q=), and then redirected to Google's top page. The same happens if your clipboard contains a URL and even if you change the search engine to Duckduckgo.

**To Reproduce**
1. Copy an arbitrary text
2. Press `p` or `P`

**Browser and Vimium version**
- Chrome: 105.0.5195.102 (Official Build) (64 bit) (cohort: Stable) 
- Vimium: 1.67

**Comment by NI57721** [comment]
Hi. I've had the same issue for these few weeks, and just searched for the cause.
This is caused by failure to fucus on the textArea below.

https://github.com/philc/vimium/blob/2c93c251118b43f447dbd0704f1ab04db466e2fd/lib/clipboard.js#L22-L33

BTW, sometimes `p` and `P` work when I open Vomnibad and close it just before using these keys.
I mean, opening Vomnibar, inputting some characters these, closing it by pressing `ESC`, and then pressing `p`/`P`.

**Comment by ArminZheng** [comment]
I'm having the same issue.

**Comment by mhalavanja** [comment]
Same is happening with Brave version 1.43.89, which is running Chromium version 105.0.5195.102 (64-bit)

**Comment by ouzkagan** [comment]
same thing happening. Windows 10 Chrome Version 105.0.5195.102 (Official Build) (64-bit). shitf + p opens new tab with URL: "https://www.google.com/search?q="

**Comment by NI57721** [comment]
I've made a fork of Vimium. It's using Clipboard API instead of execCommand.
It works well to me.
At the first time you do the paste through Vimium, you need to allow access to the clipboard.
https://github.com/NI57721/vimium/commit/c6e90010dc945edede0a10cf23f44310625f671e

If this is applied, we probably should replace execCommand("Copy") to the alternative of Clipboard API.

**Comment by adoyle-h** [comment]
@smblott-github Can you help to fix this issue?

**Comment by imagest** [comment]
Can confirm started seeing behavior for chrome since an update:
Version 105.0.5195.125 (Official Build) (x86_64)

**Comment by jianianj** [comment]
Can confirm with Version 105.0.5195.102 (Official Build) (x86_64)

**Comment by tasusu** [comment]
It looks like `p` and `P` start working again after updating Chrome to 106.0.5249.119 (64 bit). Can anyone confirm it?

**Comment by cgbahk** [comment]
> It looks like `p` and `P` start working again after updating Chrome to 106.0.5249.119 (64 bit). Can anyone confirm it?

I experienced this issue on `Chrome 106.0.5249.91 (64 bit)`
I can confirm that it is resolved with `Chrome 106.0.5249.119 (64 bit)` :tada:

**Comment by fadh1l** [comment]
Not working for me too for the past couple of weeks. 
chrome Version 105.0.5195.125 (Official Build) (64-bit)

**Comment by SimenB** [comment]
works for me again, `106.0.5249.119 (Official Build) (arm64)`. So seems Chrome fixed their regression

**Comment by NI57721** [comment]
It seems to have been fixed in 106.0.5249.119 🎉
we still need to change the way to use clipboard for Manifest V3, though.
[Log - 106.0.5249.103..106.0.5249.119 - chromium/src - Git at Google](https://chromium.googlesource.com/chromium/src/+/b90a4915e6950603c4443dca12448307b447f766)

**Comment by mhalavanja** [comment]
Works for me again, too `Version 1.44.112 Chromium: 106.0.5249.119 (Official Build) (64-bit)](https://brave.com/latest/)`

**Comment by philc** [comment]
This should be fixed permanently by #4122, which is now merged (but not yet released to the store).

**Comment by gitressa** [comment]
Thanks! But I am still seeing this in Firefox. If I press `p`, a new tab opens with https://www.google.com/webhp ...
