### ISSUE TITLE
Suggestion: Mouse hovering

### ISSUE THREAD

**Issue by nivekmai** [philc/vimium#484]
It would be awesome to have the ability to "hover" the mouse on a certain link. Lots of newer web pages have dropdowns/hover scripts that are only visible when you hover the mouse over a link (as an example, put your mouse over the "Watchers" button, and the "Watchers" tooltip expands from it.

**Comment by rajeevksahu** [comment]
They use pure cotton, fine wood made and card board containers and similar content to package your expensive items. They do not compromise with great quality and provide you with their best alternatives. Movers packers Bangalore is best choice which you can select while moving to your desire house. If you have plenty of useful items, then believe in us. We will handle them very carefully and never crack your believe in.

<a href="http://www.expert5th.in/packers-and-movers-hyderabad/" title="Movers and Packers in Hyderabad">Movers and Packers in Hyderabad</a>
<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Movers and Packers in Bangalore">Movers and Packers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Movers and Packers in Mumbai">Movers and Packers in Mumbai</a>

**Comment by rajeevksahu** [comment]
We value your cash and your emotions too. Everything you have is useful for you. Our group is so supportive and efficient in their perform. You did not encounter any Expert while choosing us. Special abilities and our popularity create us best in our perform. We use best methods and content so your items did not get any damage.

<a href="http://www.expert5th.in/packers-and-movers-gurgaon/" title="Movers and Packers in Gurgaon">Movers and Packers in Gurgaon</a>
<a href="http://www.expert5th.in/packers-and-movers-delhi/" title="Movers and Packers in Delhi">Movers and Packers in Delhi</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Movers and Packers in Pune">Movers and Packers in Pune</a>

**Comment by rajeevksahu** [comment]
This is not simple to generate income. We know the value of all the items which you have. We give unique alternatives for digital product distribution. Delicate content requirement for additional interest and we comprehend it. We also provide unique transportation to such type of fill. There are excellent chances of breaking of digital and glass components.

<a href="http://www.expert5th.in/packers-and-movers-chennai/" title="Movers and Packers in Chennai">Movers and Packers in Chennai</a>
<a href="http://www.expert5th.in/packers-and-movers-noida/" title="Movers and Packers in Noida">Movers and Packers in Noida</a>
<a href="http://www.expert5th.in/packers-and-movers-navimumbai/" title="Movers and Packers in Navi Mumbai">Movers and Packers in Navi Mumbai</a>
<a href="http://www.expert5th.in/packers-and-movers-thane/" title="Movers and Packers in Thane">Movers and Packers in Thane</a>
<a href="http://www.expert5th.in/packers-and-movers-ghaziabad/" title="Movers and Packers in Ghaziabad">Movers and Packers in Ghaziabad</a>
<a href="http://www.expert5th.in/packers-and-movers-faridabad/" title="Movers and Packers in Faridabad">Movers and Packers in Faridabad</a>

**Comment by rajeevksahu** [comment]
We package them in unique and difficult components and then provide it. Our expert is excellent in their perform. Thus there is no need to tell them what to do. You do not have any need to take additional crack from workplace to look after all the process. They are diligent as well as loyal for their duty.

<a href="http://www.expert5th.in/packers-and-movers-bangalore/" title="Packers and Movers in Bangalore">Packers and Movers in Bangalore</a>
<a href="http://www.expert5th.in/packers-and-movers-pune/" title="Packers and Movers in Pune">Packers and Movers in Pune</a>
<a href="http://www.expert5th.in/packers-and-movers-mumbai/" title="Packers and Movers in Mumbai">Packers and Movers in Mumbai</a>

**Comment by darth10** [comment]
+1

**Comment by mieubrisse** [comment]
+1

**Comment by darshandzend** [comment]
+1

**Comment by acannon828** [comment]
+1

**Comment by pratyushwy** [comment]
+1

**Comment by wcpines** [comment]
+1

**Comment by muriloime** [comment]
This would be an awesome feature.

**Comment by karlsebal** [comment]
+1

**Comment by FrankMejzlik** [comment]
+1
Yeah, this would be absolutely amazing. And also feature for focusing that link would be awesome. 

For example I need to access volume slider on youtube - I'd target it with focus and then set up volume with arrows (maybe there is another option, but I didn't figure it out yet).

**Comment by tongc** [comment]
+1

**Comment by farmic** [comment]
+1

**Comment by deiga** [comment]
If you've got nothing meaningful to add other than "+1" add the emote to the Original Post. This way we don't get unnecessary notifications.

**Comment by lantern77** [comment]
+1

**Comment by RamAnvesh** [comment]
Hi, What is the status of this issue?

**Comment by smblott-github** [comment]
It's unlikely to become a whole new command.

I'd like to do it via a command option (see option B in #2319).

**Comment by tshakah** [comment]
This is the feature I miss most from VimFX - being able to `ef` and focus pretty much anything on the page

**Comment by PrestanceDesign** [comment]
@tshakah It's one of reasons I moved to https://github.com/brookhong/Surfingkeys which permit this (Ctrl+H).

**Comment by hacksman** [comment]
+1

**Comment by A1vinSmith** [comment]
> @tshakah It's one of reasons I moved to https://github.com/brookhong/Surfingkeys which permit this (Ctrl+H).
> By the way, Vimium still is a great extension. ;)

so how did they implement this?

**Comment by PrestanceDesign** [comment]
@A1vinSmith You can check the code here https://github.com/brookhong/Surfingkeys/blob/be08a74e2cd342dd39e161b7d35070e324633369/pages/default.js#L145 and specially the 
dispatchMouseClick function https://github.com/brookhong/Surfingkeys/blob/a948e73f3c263a91e3db5e05066e1f1751cfb983/content_scripts/hints.js#L566.

**Comment by A1vinSmith** [comment]
thank you @PrestanceDesign, cheers man

**Comment by vctls** [comment]
It doesn't work that well on SurfingKey either, though...
https://github.com/brookhong/Surfingkeys/issues/961

**Comment by hjek** [comment]
[*Extended hint mode*, like `;y`, in Tridactyl](https://github.com/tridactyl/tridactyl#user-content-extended-hint-mode) sort of does this, by copy-URL-to-clipboard and other actions. Vimium is awesome too.

**Comment by gdh1995** [comment]
Hello all, #3097 has been merged, so `map X LinkHints.activateMode action=hover` (, `action=focus`, and `action=copy-text`) should work now.

**Comment by mmikeww** [comment]
issue should be closed, see comment above, #3097 works, solution is added to wiki here:
https://github.com/philc/vimium/wiki/Tips-and-Tricks#hovering-over-links-using-linkhints

**Comment by chenzhekl** [comment]
I feel #3097 did not fully solve the problem. For example, I added the following mapping to Vimium

```
map zf LinkHints.activateMode action=hover
```

On [CNN](https://edition.cnn.com/), when I hover over the `More` on the header, it should display a drop-down menu. However with `zf`, no drop-down menu appears.

**Comment by philc** [comment]
Closing this as #3097 should have solved for the bulk of cases where this is useful. If there are other cases (like the CNN one) which appear possible to fix, let's open a new issue.
